### ISSUE TITLE
Metroid Fusion ROM doesn't work

### ISSUE THREAD

**Issue by arroyjose** [flashcarts/AOS#1]
I tested the Metroid Fusion ROM with the included GBA emulator and it's not launching.  Is there a configuration issue that needs to change?

**Comment by Sanrax** [comment]
Some games require you to have a real GBA BIOS on the SD to run.

This game has been reported to not work without a bios.bin: https://old.reddit.com/r/NDSHacks/comments/lf4xln/gbarunner2_white_screen_when_trying_to_start/

Download a Gameboy Advance BIOS file, and place it in the appropriate location. (Detailed in the AOS readme's setup instructions)

**Comment by arroyjose** [comment]
That fixed it.  Thank you!
