### ISSUE TITLE
Warioware D.I.Y

### ISSUE THREAD

**Issue by DenizAydin01** [flashcarts/AOS#2]
Its just stuck at black screen 😑

**Comment by Sanrax** [comment]
Not an issue with AOS itself, we don't make tweaks to the WoodR4 kernel.

**Comment by Deletecat** [comment]
A small update about this issue. davidmorom made a patch for the wood kernel that AOS uses to make NAND games work as intended. We have made a new release (15E) to include this patch and I can confirm that Warioware D.I.Y was playable when I tried it!
