### ISSUE TITLE
[Suggestion] Soft reset files for Moonshell

### ISSUE THREAD

**Issue by MushGuyDS** [flashcarts/AOS#4]
Back in the Flashcarts subreddit some time ago I made a topic regarding soft reset files for the different versions of AOS, back when they were in flashcard-archive. After some searching, I was able to find the official soft reset files for Ace3DS+ and R4iLS to be used with Moonshell. The file for Ace3DS+ can be found in the [official website](http://ace3ds.com/ace-3ds-download.html), on a Mega download [link](https://mega.nz/file/jh9DGaQY#6883WeonYdvtOyc6QE8E_VEK2SrJcj-gEtdHXW15UXA), named R4TF.nds in /Moonshl2/resetmse. As for R4iLS, I found it in [this website](https://n2s.altervista.org/blog/moonshell-v2-09/), which gives you a [zip file](https://n2s.altervista.org/wp-content/uploads/2010/01/softreset_for_Moonshell2.zip) with a collection of soft reset files, among them, the one for R4iLS named R4TF-R4ili.nds (it has to be renamed to R4TF.nds). I experimented with the files, and I found that the file for R4iLS only works with the original flashcarts (I have the original old model, and I guess it also works with the NEW model), and not with the clone cartridges, at least not with the ones from r4isdhc.hk and r4isdhc.com.cn. As for the file for Ace3DS+, it obviously also works with Ace3DS X, and surprisingly also works with R4iLS, clones and originals. My suggestion is to include the soft reset files with the different versions of AOS to be used with Moonshell. I'll provide the files here for easy access. They only need to be renamed to make them work properly with Moonshell.
[R4TF (Ace3DS+ and R4iLS).zip](https://github.com/user-attachments/files/15527666/R4TF.Ace3DS%2B.and.R4iLS.zip)
Now we have to figure out if either one of the files also works with Gateway Blue.

PS: For both standalone R4iLS Wood and AOS to work with the old model R4iLS, a copy of _dsmenu.dat needs to be made and renamed to _ds_menu.dat. That's because the NEW model expects to load _dsmenu.dat, while the old model instead loads from _ds_menu.dat, and obviously the _ds_menu.dat from Ace3DS+ will not work properly with R4iLS. That's also how I got the soft reset file for Ace3DS+ to work with R4iLS and its clones.

**Comment by Sanrax** [comment]
Thanks, I will resolve this in AOS release 2.13-13E

**Comment by MushGuyDS** [comment]
You're welcome. Something to add: Since the official R4iLS file only works with original flashcarts, an idea for a proper soft reset file that works with both original and clone cartridges would be to modify the official Ace3DS+ file so that it loads _dsmenu.dat instead of _ds_menu.dat, since that file is shown to also work with R4iLS, originals and clones, as I explained in my previous comment. Perhaps by hex editing? Maybe with that method we could also have a soft reset file for Gateway Blue.

**Comment by Sanrax** [comment]
Soft-reset for Moonshell 2 is now available on R4iLS and Ace3DS+ based carts as of AOS release 2.13-13E.

**Comment by MushGuyDS** [comment]
An addendum to this topic: While I was searching through the R4Li website via archive.org, I was able to file a soft reset file for R4iLS from [this download](https://web.archive.org/web/20130513071201if_/http://r4li.com/downloads/Wood_R4Li_v1.56.rar) that also works with the current clones (you might remember that the one I found previously only works with the old R4iLS model), as well as Gateway Blue. Since I don't have an EX4DS yet, I cannot confirm if it works with that cartridge, but I guess the file for Ace3DS+ will work since the cartridge looks for _ds_menu.dat instead of _dsmenu.dat. Back to the soft reset file, it appears to be modified from the file for Ace3DS+ because it still says that it's loading _ds_menu.dat when it's actually loading _dsmenu.dat.

Here's the download of the file itself:
[R4TF (R4iLS, clones, Gateway Blue).zip](https://github.com/user-attachments/files/16933794/R4TF.R4iLS.clones.Gateway.Blue.zip)

**Comment by Sanrax** [comment]
The moonshell2 soft reset file for Ace+ does work on EX4DS, that's what we're using right now.

Since the current files work fine, we'll likely just keep the existing ones since these seem to be about the same thing as what you found. (Probably hex edited Ace+ reset file like ours)

**Comment by MushGuyDS** [comment]
OK, then in that case, I would suggest to add the soft reset file you currently have for R4iLS to the Gateway Blue package since I can confirm that it also works with that cartridge without a problem.

**Comment by Sanrax** [comment]
> OK, then in that case, I would suggest to add the soft reset file you currently have for R4iLS to the Gateway Blue package since I can confirm that it also works with that cartridge without a problem.

Oh, good idea. I don't want to make another release since I just made one, so I'll add it for the next AOS release.

**Comment by Deletecat** [comment]
Soft-reset in Moonshell 2 for Gateway Blue carts is now available as of AOS release 2.13-17E
