### ISSUE TITLE
MoonShell 1.71

### ISSUE THREAD

**Issue by mkeseattle** [flashcarts/AOS#5]
It would be really nice to have MoonShell 1.71 integrated, as it offers a different user interface.

https://web.archive.org/web/20070314012137/http://home.att.ne.jp/blue/moonlight/moonshell171_with_dpgtools13.zip

**Comment by Sanrax** [comment]
I mean, yes, it's different. However, it accomplishes the same purpose (media playback), and it would significantly bloat the size of AOS releases if it was added alongside MS2. It's simply not worth it for the few users that would want MS1 over MS2.

As such, I would say that if you really want MS1, just add it yourself. All you'll need to do is place `moonshl` on SD root, `moonshl.nds` into `__rpg/APP/`, and then add it to the launch menu by creating an ini for it in `__rpg\extention\_plugin_`. Remember to also add your new ini to the `plugin.odr` file.
