### ISSUE TITLE
Wood soft-reset seems to be broken on the EX4i.

### ISSUE THREAD

**Issue by SqueezePickles** [flashcarts/AOS#6]
Pressing the soft-reset hotkey seems to always get stuck on a black or white blank screen.

**Comment by Sanrax** [comment]
We think this is caused by the loader being from the R4iLS, which is looking for a `_dsmenu.dat` soft-reset target. Try making a copy of `_ds_menu.dat` and rename it to `_dsmenu.dat`, see if that fixes the soft-reset for now.

In the meantime we'll take a look at options for fixing this.

**Comment by SqueezePickles** [comment]
Yes, making a copy named "_dsmenu.dat" does fix the soft reset.

**Comment by Sanrax** [comment]
We decided to fix this issue by adding the extra dat copy, since the only other way to fix this would be to switch to the older EX4 loader. It's preferable to just have the extra copy over worse game compatibility. I've added the change to build.sh as of AceOS 2.13-16E.
