### ISSUE TITLE
Return to AOS menu

### ISSUE THREAD

**Issue by gdaleigna** [flashcarts/AOS#7]
Once I’ve launched an App from the ACE3DS+ menu, is there a way to head back to the main menu? I easily get stuck launching a title that crashes and cannot easily quit and have to reboot to 3DS mode.

Thank you

**Comment by Sanrax** [comment]
Unfortunately, there's no way to soft-reset back to the home menu from homebrew apps, except for Moonshell2. This isn't fixable.
